# Configuración de Conexión a Base de Datos MySQL (SICA)
db.engine=H2
db.url=jdbc:mysql://localhost:3306/sica?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
db.user=root
db.password=-3ta9}OK`4[Y
